#!/bin/bash

# Author: Taylor Flatt
#
# Version 1 will find any files in ROOT_DIRECTORY whose content 
# matches PATTERN and will optionally run a program on that file 
# or simply print out the relative location of the file if 
# PROGRAM isn't supplied.
#
#
# Usage: findtext ROOT_DIRECTORY PATTERN [PROGRAM]

# Check for too few parameters.
if [[ $# < 2 ]]; then
    echo "Usage: findtext ROOT_DIRECTORY PATTERN [PROGRAM]"
    exit 1
fi

# Check for too many parameters.
if [[ $# > 3 ]]; then
	echo "Usage: findtext ROOT_DIRECTORY PATTERN [PROGRAM]"
	exit 1
fi

# Assign names to the parameters.
rootdirectory=$1
pattern=$2

# If the optional paramater was given, assign a name to it. 
# We also need to find it prior to changing directories in the 
# event that it was a relative path.
if [[ $# -eq 3 ]]; then
	program=$3
	absprogdirectory=$(realpath "$program") # Get absolute path to PROGRAM.
	echo "$absprogdirectory"
	exit 1
fi

# Move into the directory that they supplied.
if ! cd "$rootdirectory" 2> /dev/null; then
	echo "Error attempting to enter the directory supplied. Are you sure that is the correct path or that  \"$rootdirectory\" is a directory?"
	exit 1
fi

# We need to check each file in the directory and see if 
# it contains PATTERN. If so, and if PROGRAM was supplied, 
# we need to run the PROGRAM on it. Otherwise we print out 
# the relative path.
for file in .* *; do
	if  grep -q "$pattern" "$file" 2> /dev/null; then
		echo "RUN PROGRAM"
	else
		echo "DON'T RUN PROGRAM"
	fi
done

exit 0

# EOF
